version: "3"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - postgres
        networks:
            - laravel

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db #db_name
            POSTGRES_USER: user #db_user
            POSTGRES_PASSWORD: pass #db_pass
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laravel

    # npm:
    #     image: node:latest
    #     container_name: npm
    #     volumes:
    #         - ./src:/var/www/html
    #     working_dir: /var/www/html
    #     entrypoint: ["npm"]

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - postgres
        working_dir: /var/www/html
        entrypoint: ["/var/www/html/artisan"]
        networks:
            - laravel
